'use strict';
/* deepseek-voice-mode orchestrator — generated static plugin OBJECT.
   Source of truth: host.js (wrapped verbatim below; do not edit this file).
   NOTE: exports the plugin OBJECT directly — a function export would be
   treated as a koishi-style plugin constructor and apply() never runs. */
module.exports = (function () {
/*
 * deepseek-voice-mode — orchestrator HOST half (dynamic Cordis plugin).
 *
 * Paste this ENTIRE file into cordis_define's code.host field (it is the body
 * of the function that must `return { inject:[...], apply(ctx){...} }`).
 *
 * Implements PROTOCOL.md §4 ("Orchestrator internals"):
 *   - voice-link helper subprocess (stdio NDJSON control + byte tunnel)
 *   - /__dsh-voice/ws upgrade route: one-time-token check, byte pipe socket<->helper
 *   - package-private RPC surface (voice.*)
 *   - IntentRouter (deterministic commands + low-reasoning LLM fallback)
 *   - ThreadManager (create / message / interrupt / status / summarize / watch)
 *   - SpeakQueue (priority preemption, 1.5s coalescing, cap) + captions ring
 *   - process-wide event wiring, dynamic Tool voice_say, /voice command,
 *     settings namespace 'voice'
 *
 * Sandbox rules honored: plain JS, no module-loading keywords, no TS/JSX; builtins only
 * (ctx, harness, console, btoa, atob, TextEncoder, TextDecoder) plus standard
 * ECMAScript intrinsics (Math, Date, JSON, Map, Set, Uint8Array, DataView,
 * Number, String, Object, Array, Promise ...); timers ONLY via inject:['timer'];
 * every service via ctx.get(name) with undefined checks; every side effect is
 * fiber-owned (ctx.effect / ctx.on / returned disposers). Live DSH objects are
 * never serialized — only scalar leaf fields are read off them.
 *
 * Every uncertain API is marked // VERIFY(<what to confirm>) — see
 * packages/orchestrator/INTEGRATION.md for the mapping to Inspect queries.
 */

return {
  // Static-boot ordering: hold activation until apply-time services exist.
  // Lazy consumers (llm/agents/sessionQuery/subagents/tools/…) stay ctx.get.
  inject: ['timer', 'settings', 'credentials', 'subprocess', 'webServer', 'commands'],
  apply(ctx) {
    /* ================================================================== *
     * 0. Constants
     * ================================================================== */
    var MAGIC = 0x0D510001;               // byte-tunnel record magic (PROTOCOL §3)
    var CONN_IDX = 1;                     // v1: one conn at a time; c1 => tunnel idx 1
    var CONN_NAME = 'c1';
    var TOKEN_TTL_MS = 60000;             // one-time handshake token lifetime
    var COALESCE_WINDOW_MS = 1500;        // SpeakQueue same-priority coalescing
    var SPEAK_CAP = 3;                    // class >= 2 drops when > 3 pending
    var QUEUE_ABS_CAP = 20;               // hard ceiling regardless of priority
    var THROTTLE_MS = 8000;               // event announcement throttle per session
    var CAPTIONS_MAX = 50;
    var ROUTER_TIMEOUT_MS = 8000;         // low-reasoning intent router budget
    var ROUTER_REASONING_EFFORT = 'low';
    var HELPER_READY_TIMEOUT_MS = 5000;
    var REPLY_WATCH_MAX_MS = 20 * 60 * 1000; // absolute lifetime of one reply watch
    var REPLY_MAX_CHARS = 1100;              // spoken reply length cap (TTS)
    // CredentialRef is a branded POSIX env-var NAME (verified dsh-credentials types).
    var REF_KEY = 'ELEVENLABS_API_KEY';
    var UPGRADE_PATH = '/__dsh-voice/ws';
    var VERBS = ['create_thread', 'message_thread', 'status', 'interrupt',
      'summarize', 'speak_only', 'route_current'];

    var enc = new TextEncoder();
    var dec = new TextDecoder();

    /* ================================================================== *
     * 1. Small pure utilities
     * ================================================================== */
    function hasOwn(obj, key) {
      return Object.prototype.hasOwnProperty.call(obj, key);
    }
    function clampInt(v, lo, hi, fallback) {
      if (typeof v !== 'number' || !isFinite(v)) return fallback === undefined ? lo : fallback;
      var n = Math.floor(v);
      if (n < lo) return lo;
      if (n > hi) return hi;
      return n;
    }
    function sink(e) {
      // swallow an error promise so it never becomes an unhandled rejection
    }
    function copyJson(value) {
      // lossless deep copy for plain JSON data only (never live DSH objects)
      return JSON.parse(JSON.stringify(value));
    }
    function hexOf(n) {
      return Math.floor(n).toString(16);
    }
    function makeToken() {
      // crypto-free one-time token (no crypto/performance builtins in the sandbox):
      // Date.now + Math.random + an in-state counter, hex-mixed, padded to 32 chars.
      // // VERIFY(global availability: Math/Date standard ECMAScript intrinsics present in
      // //   the sandbox vm; AbortController/performance/crypto absent — confirmed against
      // //   dsh-cordis-host-runner lib/types/sandbox.js: a fresh vm context + the 7 builtins)
      var parts = hexOf(Date.now()) +
        Math.random().toString(16).slice(2) +
        hexOf(Date.now() % 7919) +
        Math.random().toString(16).slice(2) +
        hexOf(state.tokenSeq++);
      var hex = parts.replace(/[^0-9a-f]/g, '0');
      while (hex.length < 32) hex += '0';
      return hex.slice(0, 32);
    }
    function tokenFromUrl(url) {
      var q = url.indexOf('?');
      if (q < 0) return null;
      var parts = url.slice(q + 1).split('&');
      for (var i = 0; i < parts.length; i++) {
        var eq = parts[i].indexOf('=');
        if (eq > 0 && parts[i].slice(0, eq) === 't') return parts[i].slice(eq + 1);
      }
      return null;
    }
    function splitPath(absolute) {
      // last slash => dir / basename (no path globals in the sandbox)
      var i = absolute.lastIndexOf('/');
      if (i <= 0) return { dir: absolute, base: absolute };
      return { dir: absolute.slice(0, i), base: absolute.slice(i + 1) };
    }
    function installedHelperPath() {
      // Static installs load this CommonJS file from packages/orchestrator.
      // Resolve the bundled helper from that location so clones and release
      // archives work without an author-specific setting.
      if (typeof __dirname === 'string' && __dirname.length) {
        return __dirname + '/../../voice-link/entry.js';
      }
      return '';
    }
    function isLoopbackAddress(value) {
      var address = String(value || '').toLowerCase();
      return address === '127.0.0.1' || address === '::1' || address === '::ffff:127.0.0.1';
    }
    function isLoopbackHost(value) {
      var host = String(value || '').toLowerCase();
      return /^localhost(?::[0-9]+)?$/.test(host) ||
        /^127\.0\.0\.1(?::[0-9]+)?$/.test(host) ||
        /^\[::1\](?::[0-9]+)?$/.test(host);
    }
    function isTruthy(v) {
      return v === true;
    }
    function isNonEmptyString(v) {
      return typeof v === 'string' && v.length > 0;
    }

    /* ================================================================== *
     * 2. Byte tunnel framing + stream scanner (PROTOCOL §3)
     * ================================================================== */
    // One binary record: magic(u32 BE) | connIdx(u8) | len(u32 BE) | payload(len)
    function TunnelEncoder() {}
    TunnelEncoder.prototype.record = function (connIdx, payload) {
      var len = payload.length;
      var out = new Uint8Array(9 + len);
      var dv = new DataView(out.buffer);
      dv.setUint32(0, MAGIC, false);
      dv.setUint8(4, connIdx & 0xFF);
      dv.setUint32(5, len, false);
      out.set(payload, 9);
      return out;
    };
    // Scanner for the helper's stdout: JSON lines (first byte '{') alternate with
    // binary records (first 4 bytes == magic). Handles chunking and resync.
    function StreamScanner() {
      this.buf = new Uint8Array(0);
    }
    StreamScanner.prototype.push = function (chunk) {
      var merged = new Uint8Array(this.buf.length + chunk.length);
      merged.set(this.buf, 0);
      merged.set(chunk, this.buf.length);
      this.buf = merged;
      this.scan();
    };
    StreamScanner.prototype.scan = function () {
      for (;;) {
        if (this.buf.length === 0) return;
        if (this.buf[0] === 0x7B /* '{' */) {
          var nl = -1;
          for (var i = 0; i < this.buf.length; i++) {
            if (this.buf[i] === 0x0A) { nl = i; break; }
          }
          if (nl < 0) return; // wait for the rest of the line
          var line = this.buf.slice(0, nl);
          this.buf = this.buf.slice(nl + 1);
          var text = dec.decode(line);
          var obj = null;
          try { obj = JSON.parse(text); } catch (e) { obj = null; }
          if (obj && this.onControl) this.onControl(obj);
          else if (this.onError) this.onError('bad control line: ' + text.slice(0, 120));
          continue;
        }
        if (this.buf.length < 9) return;
        if (this.buf[0] !== 0x0D || this.buf[1] !== 0x51 || this.buf[2] !== 0x00 || this.buf[3] !== 0x01) {
          if (this.onError) this.onError('tunnel resync: expected magic');
          this.buf = this.buf.slice(1);
          continue;
        }
        var dv = new DataView(this.buf.buffer, this.buf.byteOffset, this.buf.byteLength);
        var connIdx = dv.getUint8(4);
        var len = dv.getUint32(5, false);
        if (len > 64 * 1024 * 1024) {
          if (this.onError) this.onError('tunnel record too large: ' + len);
          this.buf = new Uint8Array(0);
          return;
        }
        if (this.buf.length < 9 + len) return;
        var payload = this.buf.slice(9, 9 + len);
        this.buf = this.buf.slice(9 + len);
        if (this.onRecord) this.onRecord(connIdx, payload);
      }
    };

    /* ================================================================== *
     * 3. FSM (disconnected -> ready -> listening -> thinking -> speaking)
     * ================================================================== */
    var FSM_LEGAL = {
      disconnected: ['ready', 'disconnected'],
      ready: ['listening', 'speaking', 'disconnected'],
      listening: ['thinking', 'disconnected', 'ready', 'speaking'],
      thinking: ['speaking', 'listening', 'disconnected', 'ready'],
      speaking: ['ready', 'listening', 'disconnected', 'thinking'],
    };
    function Fsm() {
      this.phase = 'disconnected';
    }
    Fsm.prototype.transition = function (target, reason) {
      var legal = FSM_LEGAL[this.phase] || [];
      if (legal.indexOf(target) < 0) {
        // illegal transitions are logged, never thrown
        console.log('[voice.orchestrator] fsm: ignored ' + this.phase + ' -> ' + target + (reason ? ' (' + reason + ')' : ''));
        return;
      }
      if (this.phase !== target) console.log('[voice.orchestrator] fsm: ' + this.phase + ' -> ' + target + (reason ? ' (' + reason + ')' : ''));
      this.phase = target;
    };

    /* ================================================================== *
     * 4. Captions ring buffer (last CAPTIONS_MAX, memory only)
     * ================================================================== */
    function Captions() {
      this.items = [];
    }
    Captions.prototype.push = function (level, text) {
      this.items.push({ ts: Date.now(), level: level, text: text });
      if (this.items.length > CAPTIONS_MAX) this.items.shift();
    };
    Captions.prototype.recent = function (n) {
      var k = (typeof n === 'number' && n > 0) ? n : 20;
      return this.items.slice(Math.max(0, this.items.length - k));
    };

    /* ================================================================== *
     * 5. SpeakQueue
     *    priorities: 0 user-reply / 1 lifecycle ack / 2 status / 3 ambient.
     *    Higher priority preempts lower (barge-in via tts.cancel); same class
     *    coalesces within a 1.5s window (freshest text wins); class >= 2 drops
     *    when more than SPEAK_CAP entries are queued; every entry is also
     *    mirrored to the captions ring.
     * ================================================================== */
    function SpeakQueue(state) {
      this.state = state;
      this.pending = [];
      this.active = null;
      this.seq = 0;
      this.lastPeerAck = null; // reserved (helper may echo readiness)
    }
    SpeakQueue.prototype.count = function () {
      return this.pending.length + (this.active ? 1 : 0);
    };
    SpeakQueue.prototype.push = function (text, priority) {
      var st = this.state;
      if (!isNonEmptyString(text)) return false;
      var p = clampInt(priority, 0, 3, 1);
      st.captions.push('tts', text);
      if (!st.voice.enabled) return false;              // recorded, not spoken
      if (st.muted) return false;                        // ditto
      if (p >= 2 && this.count() > SPEAK_CAP) {
        st.captions.push('status', 'announcement dropped (queue full)');
        return false;
      }
      if (this.count() >= QUEUE_ABS_CAP) return false;
      var now = Date.now();
      // preemption: strictly higher priority than the active utterance
      if (this.active && p < this.active.priority) {
        st.tunnel.sendJson({ type: 'tts.cancel', id: this.active.id });
        this.active = null;
        this.pending.unshift({ id: this.mint(), text: text, priority: p, ts: now });
        this.pump();
        return true;
      }
      // coalescing window (same class, active or pending head)
      if (this.active && this.active.priority === p && now - this.active.ts < COALESCE_WINDOW_MS) {
        this.active.text = text;
        this.active.ts = now;
        return true;
      }
      if (this.pending.length && this.pending[0].priority === p && now - this.pending[0].ts < COALESCE_WINDOW_MS) {
        this.pending[0].text = text;
        this.pending[0].ts = now;
        this.pump();
        return true;
      }
      // insert keeping FIFO within the same priority class
      var entry = { id: this.mint(), text: text, priority: p, ts: now };
      var idx = this.pending.length;
      for (var i = 0; i < this.pending.length; i++) {
        if (this.pending[i].priority >= p) { idx = i; break; }
      }
      this.pending.splice(idx, 0, entry);
      this.pump();
      return true;
    };
    SpeakQueue.prototype.mint = function () {
      this.seq += 1;
      return 'q' + this.seq;
    };
    SpeakQueue.prototype.pump = function () {
      var st = this.state;
      // v1 gate: speaking needs an attached browser session (helper TTS peer).
      // // VERIFY(helper accepts host-injected tts.speak frames via tunnel with no
      // //   browser WS peer — W1 contract; without it, announcements wait for a conn)
      if (!st.conn || !st.helper.ready) return;
      if (this.active) return;
      if (this.pending.length === 0) return;
      var entry = this.pending.shift();
      this.active = entry;
      st.fsm.transition('speaking', 'queue');
      st.tunnel.sendJson({ type: 'tts.speak', id: entry.id, text: entry.text, priority: entry.priority });
    };
    // terminal signals observed on the helper->host tunnel (tts.audio done /
    // tts.canceled / tts-scoped error) for the active utterance
    SpeakQueue.prototype.finish = function (id) {
      if (this.active && this.active.id === id) {
        this.active = null;
        this.state.fsm.transition(this.state.listening ? 'listening' : 'ready', 'tts-end');
        this.pump();
      }
    };

    /* ================================================================== *
     * 6. ThreadManager
     * ================================================================== */
    function ThreadManager(state) {
      this.state = state;
      this.registry = new Map(); // sessionId -> {title, status, lastActivity, watching}
      this.handles = new Map();  // sessionId -> AgentHandle (voice-created only)
      this.lastSpoke = new Map();// sessionId -> {kind -> ts} announcement throttle
      this.seq = 0;
    }
    ThreadManager.prototype.mintSessionId = function () {
      this.seq += 1;
      return 'voice-' + Date.now().toString(36) + '-' + hexOf(this.seq) + hexOf(Math.floor(Math.random() * 4096));
    };
    ThreadManager.prototype.mintMessageId = function () {
      this.seq += 1;
      return 'vmsg-' + Date.now().toString(36) + '-' + hexOf(this.seq);
    };
    ThreadManager.prototype.makeUserMessage = function (text) {
      return {
        id: this.mintMessageId(),
        role: 'user',
        content: [{ type: 'text', text: text }],
        source: { kind: 'plugin', plugin: 'voice' },
      };
    };
    ThreadManager.prototype.isLive = function (id) {
      var agentsSvc = this.state.svc.agents;
      if (agentsSvc) {
        try {
          var a = agentsSvc.get(id);
          return a !== undefined && a !== null;
        } catch (e) { return false; }
      }
      return this.handles.has(id);
    };
    ThreadManager.prototype.touch = function (id, patch) {
      var e = this.registry.get(id);
      if (!e) return;
      if (patch && patch.status !== undefined) e.status = patch.status;
      if (patch && patch.title !== undefined) e.title = patch.title;
      if (patch && patch.watching !== undefined) e.watching = patch.watching;
      e.lastActivity = Date.now();
    };
    // --- reply-to-speech (conversation mode) ---
    // Every voice-sent message arms a reply watch on the target session. The
    // watch only starts accumulating once the EXACT message we sent is claimed
    // into a turn ('agent/inbox/claimed' with message.id match): without that
    // gate, a question spoken while the agent is already mid-turn would pull
    // the current turn's text as its "answer". After claim, assistant/message
    // texts accumulate; when the agent goes idle the last non-empty text is
    // spoken at priority 0 (user reply), preempting acks. route_current
    // targets speak bare; other threads get an "On ..." prefix. A hard
    // lifetime caps stale watches (masked by ctx.timeout).
    ThreadManager.prototype.armReply = function (id, msgId) {
      var st = this.state;
      var w = st.replyWatch.get(id);
      if (!w) {
        w = { texts: [], armedAt: Date.now(), msgId: msgId, claimed: false };
        st.replyWatch.set(id, w);
      } else {
        w.texts = [];
        w.armedAt = Date.now();
        w.claimed = false;
      }
      if (isNonEmptyString(msgId)) w.msgId = msgId;
      var armed = w.armedAt;
      ctx.timeout(REPLY_WATCH_MAX_MS).then(function () {
        var cur = st.replyWatch.get(id);
        if (cur && cur.armedAt === armed) st.replyWatch.delete(id);
      }, function () { /* never rejects */ });
      return w;
    };
    // claim gate: the message entered a turn — from here on, assistant text
    // belongs to the reply we are waiting for
    ThreadManager.prototype.claimReply = function (id, msgId) {
      var w = this.state.replyWatch.get(id);
      if (!w || w.claimed) return;
      if (w.msgId && msgId !== w.msgId) return;
      w.claimed = true;
      w.texts = [];
    };
    ThreadManager.prototype.touchReply = function (id, ev) {
      var w = this.state.replyWatch.get(id);
      if (!w || !w.claimed) return;
      if (ev && ev.type === 'assistant/message') {
        var t = assistantTextOf(ev);
        if (isNonEmptyString(t)) w.texts.push(t);
      }
    };
    ThreadManager.prototype.clearReply = function (id) {
      this.state.replyWatch.delete(id);
    };
    // Collect the watch's last non-empty assistant text and speak it back.
    // Returns true when an utterance was actually queued.
    ThreadManager.prototype.speakReply = function (id) {
      var st = this.state;
      var w = st.replyWatch.get(id);
      if (!w) return false;
      if (!w.claimed) return false; // message not consumed yet: keep the watch for the next idle
      st.replyWatch.delete(id);
      var text = null;
      for (var i = w.texts.length - 1; i >= 0; i--) {
        var t = sanitizeSpeech(w.texts[i]);
        if (t) { text = t; break; }
      }
      if (!text) return false;
      // stale low-priority acks pushed since the watch armed would play AFTER
      // the answer (priority insert order) — drop them ("Got it." is moot once
      // the real reply speaks, and it preempts any active ack anyway)
      var pending = st.queue.pending;
      for (var j = pending.length - 1; j >= 0; j--) {
        if (pending[j].priority >= 1 && pending[j].ts >= w.armedAt) pending.splice(j, 1);
      }
      var spoken = (st.conversationId === id) ? text : 'On "' + threadName(st, id) + '": ' + text;
      var queued = st.queue.push(spoken, 0);
      if (queued) {
        // suppress the immediately-following "Thread ... is idle" announce
        this.lastSpoke.set(id, { status: Date.now(), end: Date.now(), error: Date.now(), goal: Date.now() });
      }
      return queued;
    };
    // THE single agent-create call site (PROTOCOL §4 create_thread).
    // // VERIFY(agentLoop.createAgent options + ownerCtx) — verified against
    // //   dsh-agent/lib/types/index.d.ts CreateAgentOptions: { sessionId (needs a
    // //   value), meta?: {cwd,parentSession,seedLength,origin,delegationDepth,
    // //   agentPreset}, seed?: SessionEvent[], agentOptions?: {provider,model,
    // //   maxTokens}, signal?, setup? }. ownerCtx must be a REAL cordis context:
    // //   dsh-agent-loop reads ownerCtx.fiber / ownerCtx.agents / ownerCtx.on /
    // //   ownerCtx.effect, all withheld or undeclared on the sandbox ctx façade.
    // //   That is why the primary path is ctx.get('agents').create(options): the
    // //   AgentRegistry builds the real ownerCtx (this.ctx) and Reflect.applies the
    // //   SAME loop factory createAgent(ownerCtx, options) internally.
    // //   Inspect: Service.listService agentLoop + agents.
    function createAgentOnce(state, options) {
      var agentsSvc = state.svc.agents;
      if (agentsSvc) return agentsSvc.create(options);
      var agentLoop = state.svc.agentLoop;
      if (agentLoop) return agentLoop.createAgent(ctx, options); // facade-for-ownerCtx: expected to fail; kept for parity only
      return Promise.reject(new Error('no agent factory service'));
    }
    ThreadManager.prototype.create = function (title, text) {
      var self = this;
      var st = this.state;
      var hasFactory = !!(st.svc.agents || st.svc.agentLoop);
      if (!hasFactory) return Promise.resolve({ ok: false, code: 'service_unavailable', message: 'agent factory unavailable' });
      var id = this.mintSessionId();
      var model = currentModel(st.svc); // {provider, model} or {}
      var t = isNonEmptyString(title) ? title : defaultTitle(text);
      st.fsm.transition('thinking', 'create_thread');
      // The deployment persona references {{cwd}}; agents created without it
      // assemble in _no-cwd/ and every turn dies with "prompt variable
      // \"{{cwd}}\" has no value" (verified in the live session log). Prefer the
      // user's newest real session cwd (refreshed corpus), else the sandbox
      // workspaceRoot.
      var cwd = (typeof this.defaultCwd === 'string' && this.defaultCwd.length) ? this.defaultCwd : null;
      if (!cwd) {
        try {
          var sp = st.svc.sandboxPolicy;
          if (sp && typeof sp.workspaceRoot === 'string' && sp.workspaceRoot.length) cwd = sp.workspaceRoot;
        } catch (e) { /* fall back to omitting meta (pre-fix behavior) */ }
      }
      var options = {
        sessionId: id,
        agentOptions: model,
        // Join the user's agent preset so the agent actually sees its tools/
        // prompt/skills: recording meta.agentPreset alone leaves the agent on
        // the "empty global layer" (only process-wide tools like voice_say);
        // the preset must be MOUNTED on the agent ctx at factory setup
        // (pattern: dsh-host-apiproxy createAgent setup hook).
        setup: null,
      };
      var ap = st.svc.agentPresets;
      if (ap && typeof ap.mount === 'function') {
        // Mount the DEPLOYMENT DEFAULT preset (undefined id — exactly what the
        // web GUI does for normal sessions). setup MUST await the mount: the
        // harness publishes the agent (and the model assembles its tool list)
        // only after every setup await settles — a fire-and-forget mount lands
        // after step 1 already saw the empty global layer (only voice_say).
        // Keep the function async and RETURN NOTHING: a returned mount result
        // carries a non-callable .commit -> "(intermediate value)?.commit is
        // not a function".
        options.setup = async function (agentCtx) {
          try {
            var preset = await ap.mount(agentCtx, undefined);
            st.captions.push('status', 'voice preset joined: ' + String(preset && preset.id));
          } catch (e) {
            st.captions.push('error', 'voice preset mount failed: ' + String(e && e.message || e));
          }
        };
      }
      if (cwd) {
        var meta = { cwd: cwd };
        if (typeof this.defaultPreset === 'string' && this.defaultPreset.length) meta.agentPreset = this.defaultPreset;
        options.meta = meta;
      }
      return createAgentOnce(st, options).then(function (handle) {
        self.handles.set(id, handle);
        self.registry.set(id, { title: t, status: 'running', lastActivity: Date.now(), watching: true });
        st.captions.push('status', 'thread started: ' + t);
        st.queue.push('Thread "' + t + '" started', 1);
        if (isNonEmptyString(text)) {
          // auto-send the initial message (wake) — user/plugin message shape
          // // VERIFY(agent.send UserMessage accepted by the loop; MessageId/InboxTarget
          // //   are runtime strings) — verified dsh-agent runtime-types Agent.send +
          // //   dsh-llm message.d.ts UserMessage {id,role,content,source}
          var wake = self.makeUserMessage(text);
          var live = liveAgent(st.svc, id);
          if (live) { live.send(wake, 'next-step', true); }
          else if (handle && handle.agent && handle.agent.send) { handle.agent.send(wake, 'next-step', true); }
          self.armReply(id, wake.id);
        }
        return { ok: true, id: id, title: t };
      }).catch(function (err) {
        self.registry.delete(id);
        st.captions.push('error', 'thread creation failed');
        return { ok: false, code: 'create_failed', message: String(err && err.message || err) };
      });
    };
    ThreadManager.prototype.message = function (id, text) {
      var st = this.state;
      if (!isNonEmptyString(text)) return Promise.resolve({ ok: false, code: 'bad_args', message: 'text expected' });
      var agent = liveAgent(st.svc, id);
      if (!agent) return Promise.resolve({ ok: false, code: 'no_such_thread', message: 'no live thread ' + id });
      try {
        var wake = this.makeUserMessage(text);
        agent.send(wake, 'next-step', true);
        this.touch(id, { watching: true });
        this.armReply(id, wake.id);
        st.queue.push('Got it.', 1);
        return Promise.resolve({ ok: true, id: id });
      } catch (err) {
        return Promise.resolve({ ok: false, code: 'delivery_failed', message: String(err && err.message || err) });
      }
    };
    ThreadManager.prototype.interrupt = function (id) {
      var st = this.state;
      var agent = liveAgent(st.svc, id);
      if (agent) {
        // // VERIFY(agent.cancel cause {kind:'user'} semantics for a human-requested
        // //   interrupt; keepInbox preserves pending work) — verified AgentCancelCause
        // //   {kind:'user'} in dsh-session types + Agent.cancel in dsh-agent runtime-types
        try { agent.cancel({ kind: 'user' }, { keepInbox: true }); }
        catch (err) { return Promise.resolve({ ok: false, code: 'interrupt_failed', message: String(err && err.message || err) }); }
        this.touch(id, { watching: true });
        this.clearReply(id);
        st.queue.push('Stopping that thread.', 1);
        return Promise.resolve({ ok: true, id: id });
      }
      var subagents = st.svc.subagents;
      if (subagents) {
        // // VERIFY(subagents.interrupt(targetSessionId, authority) for non-live
        // //   sessions; authority {kind:'user',parentSessionId} — the orchestrator has
        // //   no live parent Agent, so the voice session id stands in) — verified
        // //   dsh-subagent continuation.d.ts SubagentInterruptAuthority
        try {
          subagents.interrupt(id, { kind: 'user', parentSessionId: id });
          return Promise.resolve({ ok: true, id: id });
        } catch (err) {
          return Promise.resolve({ ok: false, code: 'interrupt_failed', message: String(err && err.message || err) });
        }
      }
      return Promise.resolve({ ok: false, code: 'service_unavailable', message: 'agents/subagents unavailable' });
    };
    ThreadManager.prototype.summarize = function (id) {
      var st = this.state;
      var sq = st.svc.sessionQuery;
      if (!sq) return Promise.resolve({ ok: false, code: 'service_unavailable', message: 'sessionQuery unavailable' });
      return sq.readSession(id).then(function (snap) {
        var text = foldSessionText(snap);
        if (!text) { st.queue.push('That thread has nothing new yet.', 1); return { ok: true, text: '' }; }
        st.queue.push(text, 1);
        return { ok: true, text: text.slice(0, 400) };
      }).catch(function (err) {
        return { ok: false, code: 'read_failed', message: String(err && err.message || err) };
      });
    };
    // Rebuild/refresh the registry from the live corpus (lazy; after a restart).
    // // VERIFY(sessionQuery.listSessions/readTitleSnapshots/readSession shapes) —
    // //   verified dsh-session-query types: SessionRecord{header{id,createdAt}},
    // //   SessionTitleObservationResult{status:'fulfilled', value:{title:{title}}},
    // //   SessionLogSnapshot{session, events}
    ThreadManager.prototype.refresh = function () {
      var self = this;
      var st = this.state;
      var sq = st.svc.sessionQuery;
      if (!sq) return Promise.resolve(false);
      return sq.listSessions().then(function (records) {
        // Track the newest REAL session's cwd as the deployment default for
        // voice-created agents (idempotent; `create` prefers it so threads
        // land in the user's working folder, not the sandbox root).
        var newestTs = 0;
        var recordsArr2 = records || [];
        for (var rr = 0; rr < recordsArr2.length; rr++) {
          var hd = recordsArr2[rr] && recordsArr2[rr].header;
          if (!hd || typeof hd.id !== 'string' || hd.id.indexOf('voice-') === 0) continue;
          var ts = typeof hd.createdAt === 'number' ? hd.createdAt : 0;
          if (ts < newestTs) continue;
          newestTs = ts;
          if (typeof hd.cwd === 'string' && hd.cwd.length) self.defaultCwd = hd.cwd;
          // real sessions carry the deployment preset (e.g. "cordis"); without
          // it voice agents get a bare tool surface (only voice_say — no shell/
          // file tools) and cannot do real work.
          if (typeof hd.agentPreset === 'string' && hd.agentPreset.length) self.defaultPreset = hd.agentPreset;
        }
        var statusById = new Map();
        var agentsSvc = st.svc.agents;
        if (agentsSvc) {
          try {
            var list = agentsSvc.list() || [];
            for (var i = 0; i < list.length; i++) {
              var a = list[i];
              if (a && typeof a.id === 'string') {
                statusById.set(a.id, a.status === 'running' ? 'running' : (a.status === 'idle' ? 'idle' : 'unknown'));
              }
            }
          } catch (e) { /* registry read glitch: keep going */ }
        }
        var ids = [];
        var recordsArr = records || [];
        for (var j = 0; j < recordsArr.length; j++) {
          var h = recordsArr[j] && recordsArr[j].header;
          if (!h || typeof h.id !== 'string') continue;
          if (!self.registry.has(h.id)) {
            self.registry.set(h.id, {
              title: '',
              status: statusById.get(h.id) || 'unknown',
              lastActivity: typeof h.createdAt === 'number' ? h.createdAt : 0,
              watching: false,
            });
          }
          ids.push(h.id);
        }
        if (ids.length && sq.readTitleSnapshots) {
          return sq.readTitleSnapshots(ids).then(function (obs) {
            var arr = obs || [];
            for (var k = 0; k < arr.length; k++) {
              var o = arr[k];
              if (!o || o.status !== 'fulfilled' || typeof o.sessionId !== 'string') continue;
              var title = '';
              if (o.value && o.value.title && typeof o.value.title.title === 'string') title = o.value.title.title;
              var e = self.registry.get(o.sessionId);
              if (e && title) e.title = title;
            }
            for (var pair of statusById) {
              var e2 = self.registry.get(pair[0]);
              if (e2) e2.status = pair[1];
            }
            return true;
          });
        }
        for (var pair2 of statusById) {
          var e3 = self.registry.get(pair2[0]);
          if (e3) e3.status = pair2[1];
        }
        return true;
      }).catch(function () { return false; });
    };
    ThreadManager.prototype.rows = function () {
      var out = [];
      for (var entry of this.registry) {
        var e = entry[1];
        out.push({ id: entry[0], title: e.title, status: e.status, lastActivity: e.lastActivity, watching: e.watching });
      }
      out.sort(function (x, y) { return y.lastActivity - x.lastActivity; });
      return out;
    };
    // most recent live thread (route_current default target)
    ThreadManager.prototype.current = function () {
      var rows = this.rows();
      for (var i = 0; i < rows.length; i++) {
        if (this.isLive(rows[i].id)) return rows[i];
      }
      return rows.length ? rows[0] : null;
    };
    ThreadManager.prototype.watching = function (id) {
      var e = this.registry.get(id);
      return !!e && e.watching === true;
    };
    ThreadManager.prototype.announce = function (id, kind, text) {
      // process-wide event announcements: priority 2, throttled >= 8s per session
      var st = this.state;
      if (!this.watching(id)) return false;
      if (!st.voice.enabled || st.muted || !st.voice.autoSpeakReports) return false;
      var now = Date.now();
      var last = this.lastSpoke.get(id) || {};
      if (typeof last[kind] === 'number' && now - last[kind] < THROTTLE_MS) return false;
      last[kind] = now;
      this.lastSpoke.set(id, last);
      st.queue.push(text, 2);
      return true;
    };
    ThreadManager.prototype.statusSummary = function () {
      var rows = this.rows();
      var running = 0, idle = 0;
      for (var i = 0; i < rows.length; i++) {
        if (rows[i].status === 'running') running++;
        else if (rows[i].status === 'idle') idle++;
      }
      if (rows.length === 0) return 'No threads yet.';
      var names = rows.slice(0, 3).map(function (r) { return '"' + (r.title || r.id) + '" ' + r.status; });
      var tail = rows.length > 3 ? ' and ' + (rows.length - 3) + ' more' : '';
      var text = rows.length + ' thread' + (rows.length === 1 ? '' : 's') + ' live' +
        (running ? ', ' + running + ' running' : '') + (idle ? ', ' + idle + ' idle' : '') + ': ' + names.join(', ') + tail;
      return text.slice(0, 500);
    };

    /* ================================================================== *
     * 7. IntentRouter (deterministic commands + bounded LLM fallback)
     * ================================================================== */
    var ROUTER_SYSTEM =
      'You route a spoken request spoken to a coding-assistant harness into one verb. ' +
      'Answer ONLY with one JSON object, no prose, no markdown fences:\n' +
      '{"verb":"create_thread|message_thread|status|interrupt|summarize|speak_only|route_current","threadTitle?":"string","text?":"string"}\n' +
      'Rules: creating work => create_thread (threadTitle = short title, text = the full request). ' +
      'Adding to an existing thread => message_thread (text = the message). ' +
      'Asking what is happening => status. Stopping work => interrupt. ' +
      'Summarizing a thread => summarize (threadTitle = optional thread id). ' +
      'Pure speech with no action => speak_only (text = what to say). ' +
      'Conversational chatter, questions or replies to the assistant => route_current. ' +
      'Anything uncertain => route_current (text = the raw request).';
    // // VERIFY(llm.stream GenerateOptions) — verified dsh-llm types: {provider,model,
    // //   messages, system?, temperature?, maxTokens?, stop?, signal?}; chunks are
    // //   text-delta / finish. A timeout abandons reading; no AbortSignal exists in
    // //   the sandbox, so the 8s budget is enforced by racing ctx.timeout(8000).
    // //   Inspect: Service.listService llm + agentDefaultModel.currentSelection.
    function currentModel(svc) {
      var adm = svc.agentDefaultModel;
      if (!adm) return {};
      try {
        var sel = adm.currentSelection();
        if (sel && isNonEmptyString(sel.provider) && isNonEmptyString(sel.model)) {
          return { provider: sel.provider, model: sel.model };
        }
      } catch (e) { /* fall through */ }
      return {};
    }
    function collectStream(stream) {
      var text = '';
      var done = false;
      return Promise.resolve().then(function () {
        var iter = stream[Symbol.asyncIterator] ? stream[Symbol.asyncIterator]() : stream;
        function step() {
          return iter.next().then(function (r) {
            if (r.done) return;
            var chunk = r.value;
            if (chunk && chunk.type === 'text-delta' && typeof chunk.text === 'string') text += chunk.text;
            if (chunk && chunk.type === 'finish') { done = true; return; }
            return step();
          });
        }
        return step();
      }).then(function () { return text; });
    }
    function parseRouterJson(raw) {
      if (!isNonEmptyString(raw)) return null;
      var cleaned = raw.trim();
      // strip markdown fences if the model wrapped the object
      var m = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (m) cleaned = m[1].trim();
      var start = cleaned.indexOf('{');
      var end = cleaned.lastIndexOf('}');
      if (start < 0 || end < start) return null;
      var obj = null;
      try { obj = JSON.parse(cleaned.slice(start, end + 1)); } catch (e) { return null; }
      if (!obj || typeof obj !== 'object' || VERBS.indexOf(obj.verb) < 0) return null;
      return {
        verb: obj.verb,
        threadTitle: isNonEmptyString(obj.threadTitle) ? obj.threadTitle : undefined,
        text: isNonEmptyString(obj.text) ? obj.text : undefined,
      };
    }
    /* ROUTER_CORE_START — tests execute this exact pure classifier. */
    function deterministicRoute(transcript) {
      if (!isNonEmptyString(transcript)) return null;
      var text = transcript.trim();
      var polite = '(?:(?:please|can you|could you|would you)\\s+)';

      // Explicit lifecycle commands must not depend on model latency or JSON.
      var createRe = new RegExp('^' + polite + '?(?:start|create|open|launch|spawn|make)\\s+(?:(?:a|an|another|new)\\s+)?(?:thread|task|chat|session)\\b', 'i');
      if (createRe.test(text) || /^(?:new|another)\s+(?:thread|task|chat|session)\b/i.test(text)) {
        var named = text.match(/\b(?:called|named)\s+(.+?)(?=\s+(?:to|for|that|which)\s+|[,.!?]|$)/i);
        return {
          verb: 'create_thread',
          threadTitle: named && isNonEmptyString(named[1]) ? named[1].trim() : undefined,
          text: text,
        };
      }

      var stopRe = new RegExp('^' + polite + '?(?:stop|cancel|interrupt|halt|pause)(?:\\s+(?:the|this))?(?:\\s+(?:current|active))?(?:\\s+(?:thread|task|agent|work|session))?(?:\\s+(?:called|named|about))?(?:\\s+(.+?))?[.!?]*$', 'i');
      var stop = text.match(stopRe);
      if (stop && (/^(?:please\s+)?(?:stop|cancel|interrupt|halt|pause)[.!?]*$/i.test(text) || /\b(?:thread|task|agent|work|session)\b/i.test(text))) {
        return { verb: 'interrupt', threadTitle: isNonEmptyString(stop[1]) ? stop[1].trim() : undefined };
      }

      var statusRe = new RegExp('^' + polite + '?(?:' +
        'status|(?:any\\s+)?progress|progress update|status update|any updates?|' +
        '(?:check|show|tell|give|report)(?:\\s+me)?(?:\\s+the)?\\s+(?:status|progress)|' +
        'what(?:[\\x27’]s| is)\\s+(?:the\\s+)?(?:status|progress)|' +
        'what(?:[\\x27’]s| is)\\s+(?:running|happening)|' +
        'how\\s+(?:is|are)\\b.+\\bgoing|' +
        'when\\s+there(?:[\\x27’]s| is)\\s+progress' +
        ')[.!?]*$', 'i');
      if (statusRe.test(text)) return { verb: 'status' };
      if (/^(?:(?:please|can you|could you|would you)\s+)?(?:tell|notify|update)(?:\s+me)?(?:,\s*(?:um|uh),?)?\s+when\s+there(?:['’]s| is)\s+progress[.!?]*$/i.test(text)) {
        return { verb: 'status' };
      }
      return null;
    }
    /* ROUTER_CORE_END */
    function recordRoute(state, source, verb, reason, startedAt, model) {
      var diag = {
        ts: Date.now(), source: source, verb: verb, reason: reason || null,
        elapsedMs: Math.max(0, Date.now() - startedAt),
        provider: model && model.provider || null, model: model && model.model || null,
        reasoningEffort: model && model.provider ? ROUTER_REASONING_EFFORT : null,
      };
      state.routeDiag = diag;
      var detail = reason ? ' (' + reason + ')' : '';
      state.captions.push('status', 'route: ' + verb + ' via ' + source + detail);
      console.log('[voice.router] ' + verb + ' via ' + source + detail + ' in ' + diag.elapsedMs + 'ms');
    }
    // // VERIFY(agentDefaultModel.currentSelection() exists and returns
    // //   {provider, model}) — verified dsh-agent model-selection.d.ts ModelSelection
    function IntentRouter(state) {
      this.state = state;
    }
    IntentRouter.prototype.route = function (transcript) {
      var st = this.state;
      var startedAt = Date.now();
      var local = deterministicRoute(transcript);
      if (local) {
        recordRoute(st, 'deterministic', local.verb, null, startedAt, null);
        return this.execute(transcript, local);
      }
      var llm = st.svc.llm;
      var model = currentModel(st.svc);
      if (!llm || !model.provider) {
        recordRoute(st, 'fallback', 'route_current', 'model_unavailable', startedAt, model);
        return this.execute(transcript, { verb: 'route_current', text: transcript });
      }
      var options = {
        provider: model.provider,
        model: model.model,
        purpose: 'voice-intent-router',
        reasoningEffort: ROUTER_REASONING_EFFORT,
        messages: [{ role: 'user', content: [{ type: 'text', text: transcript }] }],
        system: ROUTER_SYSTEM,
        temperature: 0,
        maxTokens: 160,
      };
      var modelResult = Promise.resolve().then(function () { return collectStream(llm.stream(options)); })
        .then(function (raw) { return { kind: 'model', raw: raw }; }, function () { return { kind: 'error' }; });
      var deadline = ctx.timeout(ROUTER_TIMEOUT_MS).then(function () { return { kind: 'timeout' }; });
      return Promise.race([modelResult, deadline]).then(function (result) {
        if (result.kind === 'error') {
          recordRoute(st, 'fallback', 'route_current', 'model_error', startedAt, model);
          return this.execute(transcript, { verb: 'route_current', text: transcript });
        }
        var parsed = result.kind === 'model' ? parseRouterJson(result.raw) : null;
        if (!parsed) {
          var reason = result.kind === 'timeout' ? 'timeout' : 'invalid_json';
          recordRoute(st, 'fallback', 'route_current', reason, startedAt, model);
          return this.execute(transcript, { verb: 'route_current', text: transcript });
        }
        recordRoute(st, 'llm', parsed.verb, null, startedAt, model);
        return this.execute(transcript, parsed);
      }.bind(this));
    };
    // verb -> service mapping (PROTOCOL §4); every service via ctx.get with
    // absence checks; nothing here may throw out of the async chain
    IntentRouter.prototype.execute = function (rawTranscript, parsed) {
      var st = this.state;
      var tm = st.threads;
      var verb = parsed.verb;
      var text = parsed.text || rawTranscript;
      if (verb === 'create_thread') {
        return tm.create(parsed.threadTitle, text).then(function (r) {
          return { verb: verb, ok: r.ok, id: r.id, title: r.title };
        });
      }
      if (verb === 'message_thread') {
        var target = resolveTarget(tm, parsed.threadTitle);
        if (!target) {
          return tm.create(null, text).then(function (r) {
            return { verb: 'create_thread', ok: r.ok, id: r.id, title: r.title };
          });
        }
        return tm.message(target.id, text).then(function (r) { return { verb: verb, ok: r.ok, id: target.id }; });
      }
      if (verb === 'status') {
        return tm.refresh().then(function () {
          var summary = tm.statusSummary();
          st.queue.push(summary, 2);
          return { verb: verb, ok: true, summary: summary };
        });
      }
      if (verb === 'interrupt') {
        var t2 = resolveTarget(tm, parsed.threadTitle);
        if (!t2) return Promise.resolve({ verb: verb, ok: false, code: 'no_such_thread' });
        return tm.interrupt(t2.id).then(function (r) { return { verb: verb, ok: r.ok, id: t2.id }; });
      }
      if (verb === 'summarize') {
        var t3 = resolveTarget(tm, parsed.threadTitle);
        if (!t3) return Promise.resolve({ verb: verb, ok: false, code: 'no_such_thread' });
        return tm.summarize(t3.id).then(function (r) { return { verb: verb, ok: r.ok, id: t3.id }; });
      }
      if (verb === 'speak_only') {
        if (isNonEmptyString(parsed.text)) st.queue.push(parsed.text, 1);
        return Promise.resolve({ verb: verb, ok: true, spoken: isNonEmptyString(parsed.text) });
      }
      // route_current: insert into the bound current thread (default: most recent
      // active thread; fallback creates one). The target becomes the voice
      // "conversation channel" so follow-up chatter stays in the same chat.
      var now = tm.current();
      if (now) {
        st.conversationId = now.id;
        return tm.message(now.id, text).then(function (r) { return { verb: verb, ok: r.ok, id: now.id, fallback: false }; });
      }
      return tm.create(null, text).then(function (r) {
        if (r.ok) st.conversationId = r.id;
        return { verb: verb, ok: r.ok, id: r.id, fallback: true };
      });
    };
    function resolveTarget(tm, hint) {
      if (isNonEmptyString(hint)) {
        if (tm.isLive(hint)) return { id: hint };
        var rows = tm.rows();
        for (var i = 0; i < rows.length; i++) {
          if (rows[i].title === hint) return { id: rows[i].id };
          if (rows[i].title && rows[i].title.indexOf(hint) >= 0) return { id: rows[i].id };
        }
      }
      return tm.current();
    }
    function defaultTitle(text) {
      if (!isNonEmptyString(text)) return 'Voice thread';
      var words = text.split(/\s+/).filter(Boolean).slice(0, 6).join(' ');
      return words.length > 40 ? words.slice(0, 40) : (words || 'Voice thread');
    }

    /* ================================================================== *
     * 8. Live-object leaf extraction helpers (never serialize live objects)
     * ================================================================== */
    function liveAgent(svc, id) {
      var agentsSvc = svc.agents;
      if (agentsSvc) {
        try {
          var a = agentsSvc.get(id);
          if (a) return a;
        } catch (e) { /* fall through */ }
      }
      var handle = state.threads.handles.get(id);
      if (handle && handle.agent) return handle.agent;
      return null;
    }
    // fold a SessionLogSnapshot into plain spoken text (scalars only)
    // // VERIFY(SessionEvent user/message + assistant/message text blocks) —
    // //   defensive leaf reads of the cloned log; dsh-session types: 'user/message'
    // //   and 'assistant/message' events carry {message:{content:[{type,text}]}}
    function foldSessionText(snap) {
      var events = (snap && snap.events) || [];
      var out = [];
      var start = Math.max(0, events.length - 40);
      for (var i = start; i < events.length; i++) {
        var ev = events[i];
        if (!ev || typeof ev.type !== 'string') continue;
        if (ev.type !== 'user/message' && ev.type !== 'assistant/message') continue;
        var msg = ev.message;
        if (!msg || !Array.isArray(msg.content)) continue;
        for (var j = 0; j < msg.content.length; j++) {
          var block = msg.content[j];
          if (block && block.type === 'text' && typeof block.text === 'string' && block.text.length) {
            out.push(block.text);
          }
        }
      }
      return out.join('\n');
    }
    // leaf extraction for reply watches: the assembled assistant message of an
    // 'assistant/message' session event (data.message.content text blocks) —
    // // VERIFY(dsh-session types SessionEventMap 'assistant/message' shape:
    // //   {turn, step, message:{id,role,content:[{type:'text',text}]}}) — verified
    function assistantTextOf(ev) {
      var data = ev && ev.data;
      var msg = data && data.message;
      if (!msg || !Array.isArray(msg.content)) return null;
      var out = '';
      for (var i = 0; i < msg.content.length; i++) {
        var b = msg.content[i];
        if (b && b.type === 'text' && typeof b.text === 'string') out += b.text;
      }
      return out.length ? out : null;
    }
    // Markdown -> speech: drop code fences (read aloud they are garbage), unwrap
    // inline code/links, strip emphasis/bullet decoration, collapse whitespace.
    function sanitizeSpeech(text) {
      if (!isNonEmptyString(text)) return '';
      var t = text
        .replace(/```[\s\S]*?```/g, ' ')
        .replace(/`([^`]*)`/g, '$1')
        .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
        .replace(/[*_~>|#]/g, ' ')
        .replace(/^\s*[-+]\s+/gm, ' ')
        .replace(/\s+/g, ' ')
        .trim();
      if (t.length > REPLY_MAX_CHARS) t = t.slice(0, REPLY_MAX_CHARS) + ' …';
      return t;
    }

    /* ================================================================== *
     * 9. Helper subprocess lifecycle
     * ================================================================== */
    // spawn config lives in ONE place (the deliverable's exact spec)
    // // VERIFY(subprocess.spawn spec + handle streams) — verified dsh-subprocess
    // //   types: SubprocessSpawnSpec {argv,cwd,stdio,graceMs,env?}; handle exposes
    // //   pid, stdin (Writable), stdout/stderr (Readable), done, terminate().
    // //   Inspect: Service.listService subprocess.
    function startHelper(state) {
      var sub = state.svc.subprocess;
      if (!sub) { console.log('[voice.orchestrator] subprocess service absent; helper disabled'); return; }
      state.voice = readVoice(state);
      state.muted = !state.voice.enabled;
      if (!state.voice.enabled) {
        state.helper.stopped = true;
        return;
      }
      // Power-state guards: never double-spawn; a hard-stopped helper stays
      // down until applyPowerState resets the flag on re-enable.
      if (state.helper.alive || state.helper.starting || state.helper.stopped) return;
      state.helper.starting = true;
      var keyPromise = state.svc.credentials
        ? state.svc.credentials.resolve(REF_KEY).catch(function () { return undefined; })
        : Promise.resolve(undefined);
      keyPromise.then(function (resolved) {
        if (state.helper.stopped) { state.helper.starting = false; return; }
        var helperPath = installedHelperPath();
        if (!isNonEmptyString(helperPath)) {
          console.error('[voice.orchestrator] bundled helper path unavailable; use the static plugin install');
          state.helper.failed = true;
          state.helper.starting = false;
          return;
        }
        var parts = splitPath(helperPath);
        var spec = {
          argv: ['node', parts.base],
          cwd: parts.dir,
          stdio: { stdin: 'pipe', stdout: 'pipe', stderr: 'pipe' },
          graceMs: 3000,
        };
        var keyValue = resolved && isNonEmptyString(resolved.value) ? resolved.value : undefined;
        if (keyValue) {
          spec.env = { ELEVENLABS_API_KEY: keyValue };
          // Voice/model selection flows to the helper via env (PROTOCOL has no
          // channel for them once attached); empty strings are omitted.
          if (isNonEmptyString(state.voice.voiceId)) spec.env.ELEVENLABS_VOICE_ID = state.voice.voiceId;
          if (isNonEmptyString(state.voice.ttsModel)) spec.env.ELEVENLABS_TTS_MODEL = state.voice.ttsModel;
        }
        // // VERIFY(credentials.resolve(ref) -> {value,source}) — verified
        // //   dsh-credentials types; CredentialRef = env-var name 'ELEVENLABS_API_KEY'
        var handle;
        try {
          handle = sub.spawn(spec);
        } catch (err) {
          console.error('[voice.orchestrator] helper spawn threw: ' + String(err && err.message || err));
          state.helper.starting = false;
          return;
        }
        state.helper.handle = handle;
        state.helper.pid = handle ? handle.pid : -1;
        if (!handle || handle.pid === -1) {
          console.error('[voice.orchestrator] helper failed to spawn (pid -1)');
          state.helper.failed = true;
          state.helper.starting = false;
          return;
        }
        // always absorb the outcome promise
        handle.done.then(function (outcome) {
          console.log('[voice.orchestrator] helper exited code=' + (outcome && outcome.exitCode) + ' signal=' + (outcome && outcome.signal));
          state.helper.alive = false;
          state.helper.ready = false;
          state.helper.starting = false;
        }, function (err) {
          console.error('[voice.orchestrator] helper spawn failure: ' + String(err && err.message || err));
          state.helper.alive = false;
          state.helper.ready = false;
          state.helper.failed = true;
          state.helper.starting = false;
        });
        if (handle.stdin) handle.stdin.on('error', function (e) { console.error('[voice.orchestrator] helper stdin error: ' + String(e && e.message || e)); });
        var scanner = new StreamScanner();
        scanner.onControl = function (obj) { handleControl(state, obj); };
        scanner.onRecord = function (connIdx, payload) { handleTunnelRecord(state, connIdx, payload); };
        scanner.onError = function (msg) { console.error('[voice.orchestrator] tunnel: ' + msg); };
        if (handle.stdout) handle.stdout.on('data', function (chunk) { scanner.push(chunk); });
        if (handle.stderr) {
          handle.stderr.setEncoding('utf8');
          handle.stderr.on('data', function (text) { console.log('[voice-link] ' + String(text).trim()); });
        }
        state.helper.alive = true;
        state.helper.failed = false;
        state.helper.starting = false;
        writeCtrl(state, { type: 'init', proto: 1, logLevel: 'info' });
        // wait (bounded) for the helper's ready line
        ctx.timeout(HELPER_READY_TIMEOUT_MS).then(function () {
          if (!state.helper.ready) console.log('[voice.orchestrator] helper not ready within ' + HELPER_READY_TIMEOUT_MS + 'ms');
        }, function () {});
      });
    }
    function stopHelper(state) {
      var h = state.helper.handle;
      state.helper.stopped = true;
      state.helper.starting = false;
      state.helper.alive = false;
      state.helper.ready = false;
      state.helper.pid = -1;
      if (h) {
        try { writeCtrl(state, { type: 'stop' }); } catch (e) { /* ignore */ }
        try { h.terminate(); } catch (e) { /* ignore */ }
        h.done.catch(function () {});
      }
      state.helper.handle = null;
      state.captions.push('status', 'voice powered off');
    }
    // Hard power semantics for the Codex-style toggle:
    //   disabled => close any browser session AND terminate the helper process
    //   (no sockets, no ElevenLabs connectivity, zero possible usage).
    //   enabled  => (re)spawn the helper; FSM returns to ready when it reports.
    function applyPowerState(state) {
      state.voice = readVoice(state);
      state.muted = !state.voice.enabled;
      if (!state.voice.enabled) {
        closeConn(state, 1000);
        stopHelper(state);
        state.fsm.transition('disconnected', 'power-off');
      } else if (!state.helper.alive && !state.helper.starting) {
        state.helper.stopped = false;
        startHelper(state);
      }
    }
    function writeCtrl(state, obj) {
      var h = state.helper.handle;
      if (!h || !h.stdin || !state.helper.alive) return;
      try { h.stdin.write(enc.encode(JSON.stringify(obj) + '\n')); }
      catch (e) { console.error('[voice.orchestrator] helper stdin write failed'); }
    }
    // helper -> host control lines (NDJSON on stdout)
    function handleControl(state, obj) {
      if (!obj || typeof obj.type !== 'string') return;
      if (obj.type === 'ready') {
        state.helper.ready = true;
        state.helper.proto = obj.proto || 0;
        state.captions.push('status', 'voice helper ready');
        if (state.helper.readyResolve) { state.helper.readyResolve(true); state.helper.readyResolve = null; }
        return;
      }
      if (obj.type === 'socket.open') {
        state.fsm.transition('ready', 'socket-open');
        return;
      }
      if (obj.type === 'socket.close') {
        closeConn(state, (obj && obj.code) || 1006);
        return;
      }
      if (obj.type === 'log') {
        console.log('[voice-link] ' + String(obj.msg || ''));
        return;
      }
      if (obj.type === 'stopped') {
        state.helper.ready = false;
        console.log('[voice.orchestrator] helper stopped');
        return;
      }
      if (obj.type === 'error') {
        state.captions.push('error', String(obj.message || 'helper error'));
        console.error('[voice.orchestrator] helper error: ' + String(obj.message || ''));
        return;
      }
    }
    // helper -> host tunnel records: raw bytes for the browser socket, plus a
    // JSON peek for WS text frames (tts.* / stt.* / session.state)
    function handleTunnelRecord(state, connIdx, payload) {
      if (!payload || payload.length === 0) return;
      if (state.conn && state.conn.idx === connIdx && !state.conn.closed) {
        try { state.conn.socket.write(relayBytes(payload)); }
        catch (e) { closeConn(state, 1006); return; }
      }
      peekWsFrame(state, payload);
    }
    // // VERIFY(W1 tunnel payload convention: complete wire bytes vs bare frame
    // //   payloads — PROTOCOL §3 says "written raw back down the socket". The host
    // //   stays compatible with either: bare '{' payloads (unframed JSON text) are
    // //   wrapped into WS text frames before socket.write; everything else is
    // //   forwarded verbatim. W1 must pick ONE convention and we validate at M0.)
    function relayBytes(payload) {
      if (payload.length > 0 && payload[0] === 0x7B) return wrapWsTextFrame(payload);
      return payload;
    }
    function wrapWsTextFrame(payload) {
      var len = payload.length;
      var header;
      if (len < 126) {
        header = new Uint8Array([0x81, len]);
      } else if (len < 65536) {
        header = new Uint8Array([
          0x81, 126,
          (len >> 8) & 0xFF, len & 0xFF,
        ]);
      } else {
        header = new Uint8Array([
          0x81, 127,
          (len / 0x100000000) & 0xFF, (len / 0x1000000) & 0xFF,
          (len / 0x10000) & 0xFF, (len / 0x100) & 0xFF, len & 0xFF,
          0, 0,
        ]);
      }
      var out = new Uint8Array(header.length + len);
      out.set(header, 0);
      out.set(payload, header.length);
      return out;
    }
    // peek browser-bound WS text frames so host-side subsystems react
    function peekWsFrame(state, payload) {
      if (!payload || payload.length === 0) return;
      if (payload[0] !== 0x7B) return; // not a JSON text frame
      var text = null;
      try { text = dec.decode(payload); } catch (e) { return; }
      var obj = null;
      try { obj = JSON.parse(text); } catch (e) { return; }
      if (!obj || typeof obj.type !== 'string') return;
      var type = obj.type;
      if (type === 'stt.committed' && typeof obj.text === 'string' && obj.text.length) {
        state.captions.push('transcript', obj.text);
        state.listening = false;
        state.fsm.transition('thinking', 'committed');
        state.router.route(obj.text).catch(function (err) {
          console.error('[voice.orchestrator] router chain failed: ' + String(err && err.message || err));
        });
        return;
      }
      if (type === 'stt.partial') {
        state.lastPartial = typeof obj.text === 'string' ? obj.text : '';
        return;
      }
      if (type === 'stt.error') {
        state.captions.push('error', 'speech error: ' + String(obj.code || 'stt') + ' ' + String(obj.message || ''));
        state.listening = false;
        state.fsm.transition(state.conn ? 'ready' : 'disconnected', 'stt-error');
        return;
      }
      if (type === 'tts.start') {
        state.fsm.transition('speaking', 'tts-start');
        return;
      }
      if (type === 'tts.audio' && obj.done === true && typeof obj.id === 'string') {
        state.queue.finish(obj.id);
        return;
      }
      if (type === 'tts.canceled' && typeof obj.id === 'string') {
        state.queue.finish(obj.id);
        return;
      }
      if (type === 'tts.error') {
        state.queue.finish(state.queue.active ? state.queue.active.id : null);
        state.captions.push('error', 'tts error: ' + String(obj.code || 'tts'));
        return;
      }
      if (type === 'session.state') {
        if (obj.state === 'listening') state.fsm.transition('listening', 'peer');
        if (obj.state === 'idle' && !state.listening) state.fsm.transition('ready', 'peer');
        return;
      }
      if (type === 'error') {
        state.captions.push('error', String(obj.message || 'voice error' + (obj.code ? ' [' + obj.code + ']' : '')));
        return;
      }
    }

    /* ================================================================== *
     * 10. Browser WebSocket upgrade route (/__dsh-voice/ws)
     * ================================================================== */
    // // VERIFY(webServer.registerUpgrade route shape) — verified dsh-host-webserver
    // //   types: WebUpgradeRoute {path, handler(req, socket, head)}; exact-path only,
    // //   duplicate paths throw, handler owns the raw socket. Inspect:
    // //   Service.listService webServer.
    function registerUpgrade(state) {
      var ws = state.svc.webServer;
      if (!ws) { console.log('[voice.orchestrator] webServer absent; ws route disabled'); return; }
      var disposer;
      try {
        disposer = ws.registerUpgrade({
          path: UPGRADE_PATH,
          handler: function (req, socket, head) { return onUpgrade(state, req, socket, head); },
        });
      } catch (err) {
        console.error('[voice.orchestrator] upgrade route failed: ' + String(err && err.message || err));
        return;
      }
      if (typeof disposer === 'function') ctx.effect(function () { return disposer; });
    }
    function onUpgrade(state, req, socket, head) {
      try {
        var token = tokenFromUrl(req.url || '');
        if (!token || !consumeToken(state, token)) {
          refuseSocket(socket, 'invalid or expired token');
          return;
        }
        if (!state.helper.alive || !state.helper.ready) {
          refuseSocket(socket, 'helper not ready');
          return;
        }
        if (state.conn && !state.conn.closed) {
          refuseSocket(socket, 'one connection at a time');
          return;
        }
        // // VERIFY(helper parses the reconstructed upstream request bytes and answers
        // //   101 via the tunnel — PROTOCOL §3: socket.attach precedes tunnel bytes;
        // //   host rebuilds the request line + raw headers + trailing head bytes)
        state.conn = { idx: CONN_IDX, socket: socket, closed: false };
        writeCtrl(state, { type: 'socket.attach', connId: CONN_NAME, url: req.url || UPGRADE_PATH });
        var requestBytes = buildRequestBytes(req, head);
        tunnelWrite(state, CONN_IDX, requestBytes);
        socket.on('data', function (chunk) {
          if (state.conn && state.conn.socket === socket && !state.conn.closed) {
            tunnelWrite(state, CONN_IDX, chunk);
          }
        });
        socket.on('error', function (e) {
          console.error('[voice.orchestrator] socket error: ' + String(e && e.message || e));
        });
        socket.on('close', function () {
          if (state.conn && state.conn.socket === socket && !state.conn.closed) {
            state.conn.closed = true;
            writeCtrl(state, { type: 'socket.detach', connId: CONN_NAME });
            state.conn = null;
            state.fsm.transition('disconnected', 'socket-close');
          }
        });
        state.fsm.transition('ready', 'connect');
      } catch (err) {
        console.error('[voice.orchestrator] upgrade handler failed: ' + String(err && err.message || err));
        refuseSocket(socket, 'internal error');
      }
    }
    function refuseSocket(socket, reason) {
      try {
        var body = 'HTTP/1.1 403 Forbidden\r\nConnection: close\r\nContent-Length: 0\r\n\r\n';
        socket.write(enc.encode(body));
        socket.end();
        socket.destroy();
      } catch (e) { try { socket.destroy(); } catch (e2) { /* ignore */ } }
      console.log('[voice.orchestrator] refused ws: ' + reason);
    }
    function buildRequestBytes(req, head) {
      var parts = [];
      parts.push(enc.encode(String(req.method || 'GET') + ' ' + String(req.url || '/') + ' HTTP/' + String(req.httpVersion || '1.1') + '\r\n'));
      var raw = req.rawHeaders || [];
      var line = '';
      for (var i = 0; i + 1 < raw.length; i += 2) {
        line += String(raw[i]) + ': ' + String(raw[i + 1]) + '\r\n';
      }
      parts.push(enc.encode(line + '\r\n'));
      if (head && head.length) parts.push(head);
      var total = 0;
      for (var j = 0; j < parts.length; j++) total += parts[j].length;
      var out = new Uint8Array(total);
      var off = 0;
      for (var k = 0; k < parts.length; k++) { out.set(parts[k], off); off += parts[k].length; }
      return out;
    }
    function closeConn(state, code) {
      if (state.conn && !state.conn.closed) {
        state.conn.closed = true;
        try { state.conn.socket.end(); state.conn.socket.destroy(); } catch (e) { /* ignore */ }
        writeCtrl(state, { type: 'socket.detach', connId: CONN_NAME });
        state.conn = null;
      }
      state.fsm.transition('disconnected', 'conn-close-' + code);
    }

    /* ================================================================== *
     * 11. One-time handshake tokens (voice.handshake RPC)
     * ================================================================== */
    function pruneTokens(state) {
      var now = Date.now();
      for (var entry of state.tokens) {
        if (entry[1] < now) state.tokens.delete(entry[0]);
      }
    }
    function mintToken(state) {
      pruneTokens(state);
      var token = makeToken();
      state.tokens.set(token, Date.now() + TOKEN_TTL_MS);
      return token;
    }
    function consumeToken(state, token) {
      var expires = state.tokens.get(token);
      if (expires === undefined) return false;
      state.tokens.delete(token);
      return Date.now() < expires;
    }

    /* ================================================================== *
     * 12. Tunnel writer (host -> helper binary records + injected frames)
     * ================================================================== */
    var tunnel = {
      write: function (connIdx, payload) {
        var h = state.helper.handle;
        if (!h || !h.stdin || !state.helper.alive) return false;
        try { h.stdin.write(tunnel.encoder.record(connIdx, payload)); return true; }
        catch (e) { return false; }
      },
      encoder: null,
      // browser-style C->S messages injected by the HOST (tts.speak, listen.*,
      // tts.cancel) ride the tunnel in bare JSON payload form; the helper parses
      // records whose first byte is '{' are interpreted like host-injected WS text frames.
      // // VERIFY(helper accepts host-injected browser-style frames without a
      // //   masking WS frame — W1 must treat first-byte-{ records accordingly)
      sendJson: function (msg) {
        if (!state.conn || state.conn.closed) return false;
        return tunnel.write(CONN_IDX, enc.encode(JSON.stringify(msg)));
      },
    };
    tunnel.encoder = new TunnelEncoder();
    function tunnelWrite(state, connIdx, payload) { return tunnel.write(connIdx, payload); }

    /* ================================================================== *
     * 13. Settings namespace 'voice' (PROTOCOL §4 defaults)
     * ================================================================== */
    // // VERIFY(settings.register schema construct) — dsh-settings resolve() CALLS
    // //   schema(mergedValue) (lib/types/index.js line ~520), so a callable identity
    // //   function with a .toJSON() description is accepted in place of a schemastery
    // //   Schema object (no schema builder can be pulled into the sandbox). If the
    // //   runtime rejects the shape, registration fails here and every voice.config
    // //   RPC degrades to 'unavailable' — nothing else is affected.
    // //   Inspect: Service.listService settings. Also note: PROTOCOL §4 lists the
    // //   namespace fields. The helper path is derived from this installed plugin
    // //   instead of being user-configurable through the browser control plane.
    var VOICE_DEFAULTS = {
      enabled: true,
      mode: 'ptt',
      voiceId: '21m00Tcm4TlvDq8ikWAM',
      ttsModel: 'eleven_flash_v2_5',
      sttModel: 'scribe_v2_realtime',
      sttLanguage: undefined,
      vadSensitivity: 0.5,
      dailyCreditCap: undefined,
      autoSpeakReports: true,
      hotkey: '',
    };
    var VOICE_TYPES = {
      enabled: { type: 'boolean', description: 'Master switch for the voice layer' },
      mode: { type: 'string', description: 'push-to-talk or always-on (v1: ptt)' },
      voiceId: { type: 'string', description: 'ElevenLabs voice id' },
      ttsModel: { type: 'string', description: 'ElevenLabs TTS model' },
      sttModel: { type: 'string', description: 'ElevenLabs STT model' },
      sttLanguage: { type: 'string', description: 'Optional STT language hint' },
      vadSensitivity: { type: 'number', description: 'Voice activity detection sensitivity 0..1' },
      dailyCreditCap: { type: 'number', description: 'Optional daily credit cap in credits' },
      autoSpeakReports: { type: 'boolean', description: 'Speak thread/goal status announcements' },
      hotkey: { type: 'string', description: 'Global push-to-talk hotkey' },
    };
    function makeSettingsSchema(defs) {
      var fn = function identityResolver(value) { return value; };
      fn.toJSON = function () {
        var props = {};
        for (var key of Object.keys(defs)) props[key] = defs[key];
        return { type: 'object', description: 'voice layer settings', properties: props };
      };
      return fn;
    }
    function readVoice(state) {
      var svc = state.svc.settings;
      var base = {};
      for (var key of Object.keys(VOICE_DEFAULTS)) base[key] = VOICE_DEFAULTS[key];
      if (!svc) return base;
      var v = null;
      try { v = svc.get('voice'); } catch (e) { return base; }
      if (!v || typeof v !== 'object') return base;
      var out = {};
      for (var k of Object.keys(VOICE_DEFAULTS)) {
        var raw = v[k];
        var def = VOICE_DEFAULTS[k];
        if (typeof def === 'boolean') out[k] = raw === true;
        else if (typeof def === 'number') out[k] = (typeof raw === 'number' && isFinite(raw)) ? raw : def;
        else out[k] = (typeof raw === 'string') ? raw : def;
      }
      return out;
    }
    function registerSettings(state) {
      var svc = state.svc.settings;
      if (!svc) { console.log('[voice.orchestrator] settings service absent'); return; }
      try {
        svc.register('voice', makeSettingsSchema(VOICE_TYPES), { base: copyJson(VOICE_DEFAULTS) });
        state.settingsRegistered = true;
      } catch (err) {
        // a duplicate namespace or a rejected schema degrades gracefully
        console.error('[voice.orchestrator] settings register failed: ' + String(err && err.message || err));
        state.settingsRegistered = false;
      }
    }

    /* ================================================================== *
     * 14. RPC surface (harness.handle — package-private Client->Host JSON)
     * ================================================================== */
    // // VERIFY(harness.handle(method, handler)) — verified dsh-cordis-host-runner
    // //   guard.js: validates the method name, clone-wraps the result; returns the
    // //   disposer. Inspect: Builtin.listBuiltins (host).
    function registerRpc(state) {
      var handlers = {
        'voice.handshake': function () {
          return { ok: true, token: mintToken(state), expiresIn: TOKEN_TTL_MS / 1000 };
        },
        'voice.state.get': function () {
          return { ok: true, state: snapshotState(state) };
        },
        'voice.listen.start': function (args) {
          var v = readVoice(state);
          if (!v.enabled) return { ok: false, error: { code: 'disabled', message: 'voice disabled' } };
          if (!state.conn || state.conn.closed) return { ok: false, error: { code: 'no_session', message: 'no active voice session' } };
          var msg = { type: 'listen.start', commit: 'vad' };
          if (args && (args.commit === 'manual' || args.commit === 'vad')) msg.commit = args.commit;
          if (args && isNonEmptyString(args.language)) msg.language = args.language;
          tunnel.sendJson(msg);
          state.listening = true;
          state.fsm.transition('listening', 'rpc-listen-start');
          return { ok: true };
        },
        'voice.listen.stop': function () {
          if (!state.conn || state.conn.closed) return { ok: false, error: { code: 'no_session', message: 'no active voice session' } };
          tunnel.sendJson({ type: 'listen.stop' });
          state.listening = false;
          return { ok: true };
        },
        'voice.tts.say': function (args) {
          if (!args || !isNonEmptyString(args.text)) return { ok: false, error: { code: 'bad_args', message: 'text expected' } };
          state.queue.push(args.text, clampInt(args.priority, 0, 3, 0));
          return { ok: true, id: state.queue.active ? state.queue.active.id : null };
        },
        'voice.threads.list': function () {
          return state.threads.refresh().then(function () {
            return { ok: true, threads: state.threads.rows() };
          });
        },
        'voice.thread.create': function (args) {
          var title = args && typeof args.title === 'string' ? args.title : '';
          var text = args && typeof args.text === 'string' ? args.text : '';
          return state.threads.create(title, text);
        },
        'voice.thread.message': function (args) {
          if (!args || !isNonEmptyString(args.id)) return { ok: false, code: 'bad_args', message: 'id expected' };
          return state.threads.message(args.id, args.text || '');
        },
        'voice.thread.interrupt': function (args) {
          if (!args || !isNonEmptyString(args.id)) return { ok: false, code: 'bad_args', message: 'id expected' };
          return state.threads.interrupt(args.id);
        },
        'voice.history.recent': function (args) {
          var n = args && typeof args.limit === 'number' ? Math.floor(args.limit) : undefined;
          return { ok: true, captions: state.captions.recent(n), partial: state.lastPartial || '' };
        },
        'voice.config.get': function () {
          if (!state.settingsRegistered) return { ok: false, error: { code: 'settings_unavailable', message: 'voice settings not registered' } };
          return { ok: true, config: readVoice(state) };
        },
        'voice.config.set': function (args) {
          var svc = state.svc.settings;
          if (!state.settingsRegistered || !svc) return { ok: false, error: { code: 'settings_unavailable', message: 'voice settings not registered' } };
          if (!args || typeof args.patch !== 'object' || args.patch === null) {
            return { ok: false, error: { code: 'bad_args', message: 'patch expected' } };
          }
          return svc.update('voice', args.patch).then(function () {
            applyPowerState(state);
            return { ok: true, config: readVoice(state) };
          }).catch(function (err) {
            return { ok: false, error: { code: 'update_failed', message: String(err && err.message || err) } };
          });
        },
        'voice.diag.ping': function () {
          return {
            ok: true,
            pong: true,
            ts: Date.now(),
            fsm: state.fsm.phase,
            helper: { running: state.helper.alive, ready: state.helper.ready, pid: state.helper.pid, failed: state.helper.failed },
            conn: !!(state.conn && !state.conn.closed),
            queue: { pending: state.queue.pending.length, active: !!state.queue.active },
            threads: state.threads.registry.size,
            tokens: state.tokens.size,
            router: state.routeDiag,
          };
        },
      };
      var names = Object.keys(handlers);
      // Transport A (static composition): plain JSON-over-HTTP routes on the
      // harness's own server — same-origin fetch from the client half. One
      // prefix route; method comes from the path suffix. Works in BOTH modes.
      var wsSvc = state.svc.webServer;
      if (wsSvc && typeof wsSvc.register === 'function') {
        try {
          var routeDisposer = wsSvc.register({
            kind: 'prefix',
            path: '/__dsh-voice/rpc',
            handler: function (req, res) { return handleRpcHttp(state, req, res, handlers); },
          });
          if (typeof routeDisposer === 'function') ctx.effect(function () { return routeDisposer; });
        } catch (err) {
          console.error('[voice.orchestrator] rpc http route failed: ' + String(err && err.message || err));
        }
      }
      // Transport B (dynamic runner): package-private host.call plumbing.
      if (typeof harness !== 'undefined' && harness && typeof harness.handle === 'function') {
        ctx.effect(function () {
          for (var i = 0; i < names.length; i++) {
            (function (name) {
              var disposer = harness.handle(name, function (args) {
                var fn = handlers[name];
                return Promise.resolve().then(function () { return fn(args); }).catch(function (err) {
                  return { ok: false, error: { code: 'handler_error', message: String(err && err.message || err) } };
                });
              });
              batchDisposers.push(disposer);
            })(names[i]);
          }
          return function () {
            for (var j = 0; j < batchDisposers.length; j++) {
              try { if (batchDisposers[j]) batchDisposers[j](); } catch (e) { /* ignore */ }
            }
            batchDisposers.length = 0;
          };
        });
      }
    }
    function handleRpcHttp(state, req, res, handlers) {
      // POST /__dsh-voice/rpc/<method>  body: JSON args  → JSON result
      var urlPath = String(req.url || '');
      var qIdx = urlPath.indexOf('?');
      if (qIdx >= 0) urlPath = urlPath.slice(0, qIdx);
      var methodName = urlPath.replace(/^\/__dsh-voice\/rpc\/?/, '');
      function reply(status, obj) {
        try {
          var bodyText = JSON.stringify(obj);
          res.writeHead(status, { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(bodyText) });
          res.end(bodyText);
        } catch (e) { try { res.end(); } catch (e2) { /* ignore */ } }
      }
      if (req.method !== 'POST') { reply(405, { ok: false, error: { code: 'method_not_allowed', message: 'POST expected' } }); return; }
      var headers = req.headers || {};
      var remoteAddress = req.socket && req.socket.remoteAddress;
      if (!isLoopbackAddress(remoteAddress)) {
        reply(403, { ok: false, error: { code: 'loopback_required', message: 'voice RPC is local-only' } });
        return;
      }
      var host = String(headers.host || '');
      if (!isLoopbackHost(host)) {
        reply(403, { ok: false, error: { code: 'loopback_host_required', message: 'localhost host required' } });
        return;
      }
      var origin = String(headers.origin || '');
      var fetchSite = String(headers['sec-fetch-site'] || '').toLowerCase();
      if (!origin || (origin !== 'http://' + host && origin !== 'https://' + host)) {
        reply(403, { ok: false, error: { code: 'origin_denied', message: 'same-origin request required' } });
        return;
      }
      if (fetchSite && fetchSite !== 'same-origin') {
        reply(403, { ok: false, error: { code: 'origin_denied', message: 'cross-site request denied' } });
        return;
      }
      var contentType = String(headers['content-type'] || '').toLowerCase();
      if (contentType.indexOf('application/json') !== 0) {
        reply(415, { ok: false, error: { code: 'content_type_required', message: 'application/json expected' } });
        return;
      }
      var fn = handlers[methodName];
      if (!fn) { reply(404, { ok: false, error: { code: 'no_such_method', message: methodName || '(empty)' } }); return; }
      var chunks = [];
      var total = 0;
      var done = false;
      req.on('data', function (c) {
        total += c.length;
        if (total > 1048576) { if (!done) { done = true; reply(413, { ok: false, error: { code: 'too_large', message: 'body > 1MiB' } }); req.destroy(); } return; }
        chunks.push(c);
      });
      req.on('end', function () {
        if (done) return;
        done = true;
        var args = null;
        var raw = Buffer.concat(chunks).toString('utf8');
        if (raw.length) { try { args = JSON.parse(raw); } catch (e) { reply(400, { ok: false, error: { code: 'bad_json', message: String(e && e.message || e) } }); return; } }
        Promise.resolve().then(function () { return fn(args); }).then(function (value) {
          reply(200, value === undefined ? { ok: true } : value);
        }, function (err) {
          reply(200, { ok: false, error: { code: 'handler_error', message: String(err && err.message || err) } });
        });
      });
      req.on('error', function () { if (!done) { done = true; try { res.destroy(); } catch (e) { /* ignore */ } } });
    }
    function snapshotState(state) {
      return {
        phase: state.fsm.phase,
        muted: state.muted,
        listening: state.listening,
        partial: state.lastPartial || '',
        captions: state.captions.recent(50),
        speaking: state.queue.active ? state.queue.active.text : '',
        helper: { running: state.helper.alive, ready: state.helper.ready, pid: state.helper.pid },
        threads: state.threads.rows().length,
        enabled: state.voice.enabled,
        mode: state.voice.mode,
        router: state.routeDiag,
      };
    }

    /* ================================================================== *
     * 15. Dynamic Tool voice_say + /voice command
     * ================================================================== */
    // // VERIFY(harness.defineTool DSL + registerTool contract) — verified
    // //   dsh-cordis-host-runner guard.js: options {name?, description?,
    // //   parameters (root {type:'object', properties} + optional needs-array),
    // //   output {schema, render(args,value)->ContentBlock[], presentationMeta?},
    // //   execute(args,exec)->JSON}; registerTool(ctx, tool) returns the disposer.
    // //   Inspect: Builtin.listBuiltins (host) + Tool.listTools for conflicts.
    function registerTool(state) {
      var tool;
      var build = function () { return {
          name: 'voice_say',
          description: 'Queue a short spoken announcement (TTS). The orchestrator speaks it over the voice channel and mirrors it to captions.',
          parameters: {
            type: 'object',
            properties: {
              text: { type: 'string', description: 'The text to speak aloud (keep short)' },
              priority: { type: 'integer', description: '0 user reply, 1 ack, 2 status, 3 ambient (default 1)' },
            },
          },
          output: {
            schema: {
              type: 'object',
              properties: {
                queued: { type: 'boolean' },
                id: { type: 'string' },
              },
            },
            render: function (args, value) {
              return [{ type: 'text', text: value.queued ? 'Announcement queued for voice.' : 'Voice is disabled / muted; announcement recorded to captions only.' }];
            },
          },
          execute: function (args) {
            if (!args || !isNonEmptyString(args.text)) return { queued: false, id: null };
            var queued = state.queue.push(args.text, clampInt(args.priority, 0, 3, 1));
            return { queued: queued, id: state.queue.active ? state.queue.active.id : null };
          },
        }; };
      // Dynamic runner: normalized+marked through the harness pair. Static
      // composition: plain tools.register with the same definition shape.
      if (typeof harness !== 'undefined' && harness && typeof harness.defineTool === 'function') {
        try {
          var tool = harness.defineTool(build());
          var disposer = harness.registerTool(ctx, tool);
          ctx.effect(function () { return disposer; });
        } catch (err) {
          console.error('[voice.orchestrator] tool register (dynamic) failed: ' + String(err && err.message || err));
        }
        return;
      }
      var toolsSvc = state.svc.tools;
      if (!toolsSvc || typeof toolsSvc.register !== 'function') {
        console.log('[voice.orchestrator] tools service absent; voice_say disabled');
        return;
      }
      try {
        var d2 = toolsSvc.register(build());
        if (typeof d2 === 'function') ctx.effect(function () { return d2; });
      } catch (err) {
        console.error('[voice.orchestrator] tool register (static) failed: ' + String(err && err.message || err));
      }
    }
    // // VERIFY(commands.register CommandDefinition) — verified dsh-commands types:
    // //   {name (no slash), description, handler(invocation)->CommandResult
    // //   {kind:'success'|'error', text?}}. Inspect: Service.listService commands.
    function registerCommand(state) {
      var cmds = state.svc.commands;
      if (!cmds) { console.log('[voice.orchestrator] commands service absent'); return; }
      var disposer;
      try {
        disposer = cmds.register({
          name: 'voice',
          description: 'Control the voice layer: /voice on|off|status|say <text>',
          handler: function (invocation) {
            var input = (invocation && typeof invocation.rawInput === 'string' ? invocation.rawInput : '').trim();
            var space = input.indexOf(' ');
            var sub = (space < 0 ? input : input.slice(0, space)).toLowerCase();
            var rest = space < 0 ? '' : input.slice(space + 1).trim();
            if (sub === 'on' || sub === 'off') {
              var svc = state.svc.settings;
              if (!state.settingsRegistered || !svc) return { kind: 'error', text: 'voice settings unavailable' };
              return svc.update('voice', { enabled: sub === 'on' }).then(function () {
                applyPowerState(state);
                return { kind: 'success', text: 'voice ' + (sub === 'on' ? 'enabled' : 'powered off') };
              }).catch(function (err) {
                return { kind: 'error', text: String(err && err.message || err) };
              });
            }
            if (sub === 'status') {
              var s = snapshotState(state);
              return { kind: 'success', text: 'voice ' + s.phase + (s.muted ? ' (muted)' : '') + ', helper ' + (s.helper.ready ? 'ready' : 'down') + ', ' + s.threads + ' thread(s)' };
            }
            if (sub === 'say') {
              if (!rest) return { kind: 'error', text: '/voice say needs text' };
              state.queue.push(rest, 1);
              return { kind: 'success', text: 'speaking: ' + rest.slice(0, 60) };
            }
            return { kind: 'error', text: 'usage: /voice on|off|status|say <text>' };
          },
        });
      } catch (err) {
        console.error('[voice.orchestrator] command register failed: ' + String(err && err.message || err));
        return;
      }
      if (typeof disposer === 'function') ctx.effect(function () { return disposer; });
    }

    /* ================================================================== *
     * 16. Process-wide event wiring (announcements, priority 2)
     * ================================================================== */
    // // VERIFY(Host event payloads) — verified Event.listEvents: agent/status
    // //   {agent,status}, agent/error {agent,turn,step,error}, agent/turn-stopping
    // //   {agent,turn,signal} (serial), subagent/end {info:{id,stopReason}},
    // //   goal/changed {agent,change}. Only scalar leaves are read off live agents.
    function registerEvents(state) {
      ctx.on('agent/status', function (payload) {
        try {
          var agent = payload && payload.agent;
          var id = agent && typeof agent.id === 'string' ? agent.id : null;
          if (!id) return;
          var status = payload.status === 'running' ? 'running' : (payload.status === 'idle' ? 'idle' : 'unknown');
          var entry = state.threads.registry.get(id);
          if (entry) { entry.status = status; entry.lastActivity = Date.now(); }
          // conversation replies: when a watched thread's agent goes idle, speak
          // the last assistant text back (priority 0 user reply). Must run before
          // the status announce so the reply suppresses the "is idle" chatter.
          if (status === 'idle') {
            var w = state.replyWatch.get(id);
            if (w) {
              if (Date.now() - w.armedAt > REPLY_WATCH_MAX_MS) state.replyWatch.delete(id);
              else state.threads.speakReply(id);
            }
          }
          state.threads.announce(id, 'status', 'Thread "' + threadName(state, id) + '" is ' + status);
        } catch (e) { console.error('[voice.orchestrator] agent/status listener: ' + String(e && e.message || e)); }
      });
      ctx.on('agent/error', function (payload) {
        try {
          var id = payload && payload.agent && typeof payload.agent.id === 'string' ? payload.agent.id : null;
          if (!id) return;
          state.threads.announce(id, 'error', 'Thread "' + threadName(state, id) + '" hit an error');
          state.captions.push('error', 'thread error: ' + threadName(state, id));
        } catch (e) { console.error('[voice.orchestrator] agent/error listener: ' + String(e && e.message || e)); }
      });
      ctx.on('agent/turn-stopping', function (payload) {
        try {
          var id = payload && payload.agent && typeof payload.agent.id === 'string' ? payload.agent.id : null;
          if (!id) return;
          var entry = state.threads.registry.get(id);
          if (entry) { entry.lastActivity = Date.now(); }
        } catch (e) { /* ignore */ }
      });
      ctx.on('subagent/end', function (info) {
        try {
          var childId = info && typeof info.id === 'string' ? info.id : null;
          if (!childId) return;
          var reason = info.stopReason === 'complete' ? 'finished' : 'settled';
          state.threads.announce(childId, 'end', 'Thread "' + threadName(state, childId) + '" ' + reason);
        } catch (e) { console.error('[voice.orchestrator] subagent/end listener: ' + String(e && e.message || e)); }
      });
      ctx.on('goal/changed', function (payload) {
        try {
          var id = payload && payload.agent && typeof payload.agent.id === 'string' ? payload.agent.id : null;
          if (!id) return;
          // // VERIFY(goal/changed change field vocabulary) — defensively read only
          // //   scalar fields; the change object shape is merge-extensible
          var label = '';
          var change = payload.change;
          if (change) {
            if (typeof change.action === 'string' && change.action.length) label = change.action;
            else if (typeof change.phase === 'string' && change.phase.length) label = change.phase;
            else label = 'changed';
          }
          state.threads.announce(id, 'goal', 'Goal ' + label + ' on"' + threadName(state, id) + '"');
        } catch (e) { /* ignore */ }
      });
      // / VERIFY(SessionEvent publication) — dsh-session publishes every committed
      // /   event to the process bus, scoped to its live session; listeners receive
      // /   (session, event) with event = {type, seq, time, data} (verified
      // /   dsh-session lib/types/index.js append(): callbackArgs = [this, event]).
      // /   This is how the web GUI streams live session events, so the watch can
      // /   accumulate the conversation's assistant text in real time.
      ctx.on('session/event', function (session, event) {
        try {
          var sid = session && typeof session.id === 'string' ? session.id : null;
          if (!sid) return;
          var w = state.replyWatch.get(sid);
          if (!w) return;
          if (Date.now() - w.armedAt > REPLY_WATCH_MAX_MS) { state.replyWatch.delete(sid); return; }
          state.threads.touchReply(sid, event);
        } catch (e) { /* observer must never throw into session publication */ }
      });
      // claim gate for reply watches: the exact message we sent entered a turn.
      // // VERIFY('agent/inbox/claimed' payload) — dsh-agent-loop Inbox emits
      // //   {message, turn} agent-scoped (agent injected); the claim fires when
      // //   the loop pulls the queued message into a turn.
      ctx.on('agent/inbox/claimed', function (payload) {
        try {
          var agent = payload && payload.agent;
          var id = agent && typeof agent.id === 'string' ? agent.id : null;
          if (!id) return;
          var m = payload.message;
          var msgId = m && typeof m.id === 'string' ? m.id : null;
          if (!msgId) return;
          state.threads.claimReply(id, msgId);
        } catch (e) { /* observer never throws */ }
      });
    }
    function threadName(state, id) {
      var entry = state.threads.registry.get(id);
      if (entry && entry.title) return entry.title;
      return id.slice(0, 12);
    }

    /* ================================================================== *
     * 17. apply(): assemble everything on the owning fiber
     * ================================================================== */
    var state = {
      tokenSeq: 1,
      svc: {
        settings: ctx.get('settings'),
        credentials: ctx.get('credentials'),
        subprocess: ctx.get('subprocess'),
        webServer: ctx.get('webServer'),
        commands: ctx.get('commands'),
        llm: ctx.get('llm'),
        agentLoop: ctx.get('agentLoop'),
        tools: ctx.get('tools'),
        agents: ctx.get('agents'),
        sessions: ctx.get('sessions'),
        sessionQuery: ctx.get('sessionQuery'),
        subagents: ctx.get('subagents'),
        agentDefaultModel: ctx.get('agentDefaultModel'),
        agentPresets: ctx.get('agentPresets'),
        sandboxPolicy: ctx.get('sandboxPolicy'),
      },
      voice: {},
      settingsRegistered: false,
      tokens: new Map(),
      fsm: new Fsm(),
      captions: new Captions(),
      muted: false,
      listening: false,
      lastPartial: '',
      // The session the voice channel is "in conversation with" (last route_current
      // target). Its replies are spoken bare; other threads get an "On ..." prefix.
      conversationId: null,
      // sessionId -> { texts: string[], armedAt: number } armed by every voice
      // message; fed by the session/event firehose; spoken on agent idle.
      replyWatch: new Map(),
      conn: null,
      helper: {
        handle: null,
        pid: -1,
        alive: false,
        ready: false,
        failed: false,
        stopped: false,
        proto: 0,
        readyResolve: null,
      },
      queue: null,
      threads: null,
      router: null,
      routeDiag: null,
      tunnel: tunnel,
    };
    var batchDisposers = [];
    registerSettings(state);
    state.voice = readVoice(state);
    state.muted = !state.voice.enabled;
    state.queue = new SpeakQueue(state);
    state.threads = new ThreadManager(state);
    state.threads.defaultCwd = null;   // seeded by refresh(); see ThreadManager.refresh
    state.threads.defaultPreset = null; // seeded by refresh(); see ThreadManager.refresh
    state.threads.refresh().catch(function () { /* best-effort cwd/preset corpus */ });
    state.router = new IntentRouter(state);

    registerRpc(state);
    registerTool(state);
    registerCommand(state);
    registerUpgrade(state);
    registerEvents(state);
    // helper subprocess: spawned on the owning fiber, killed on teardown
    ctx.effect(function () {
      startHelper(state);
      return function () { stopHelper(state); };
    });

    console.log('[voice.orchestrator] activated (voice plugin host half)');
  },
};
})();
